# Generated by Django 5.2.14 on 2026-06-02 04:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inquiry_type', models.CharField(choices=[('viewing', 'Razgledanje'), ('consultation', 'Konsultacija'), ('private_collection', 'Privatna kolekcija'), ('general', 'Opšte')], max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('preferred_language', models.CharField(choices=[('sr', 'Srpski'), ('en', 'Engleski'), ('fr', 'Francuski')], max_length=5)),
                ('budget_range', models.CharField(blank=True, max_length=100)),
                ('property_type_wanted', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('new', 'Novo'), ('contacted', 'Kontaktiran'), ('in_progress', 'U toku'), ('closed', 'Zatvoreno')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='properties.property')),
            ],
            options={
                'verbose_name': 'Upit',
                'verbose_name_plural': 'Upiti',
                'ordering': ['-created_at'],
            },
        ),
    ]
