# Generated by Django 5.2.14 on 2026-06-05 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
        ('properties', '0002_alter_property_area_sqm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='budget_range',
            field=models.CharField(blank=True, max_length=100, verbose_name='Budžet'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Datum upita'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='inquiry_type',
            field=models.CharField(choices=[('viewing', 'Razgledanje'), ('consultation', 'Konsultacija'), ('private_collection', 'Privatna kolekcija'), ('general', 'Opšte')], max_length=20, verbose_name='Tip upita'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP adresa'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='message',
            field=models.TextField(verbose_name='Poruka'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Ime i prezime'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Napomene'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='preferred_language',
            field=models.CharField(choices=[('sr', 'Srpski'), ('en', 'Engleski'), ('fr', 'Francuski')], max_length=5, verbose_name='Željeni jezik'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='properties.property', verbose_name='Nekretnina'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='property_type_wanted',
            field=models.CharField(blank=True, max_length=100, verbose_name='Željeni tip nekretnine'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('new', 'Novo'), ('contacted', 'Kontaktiran'), ('in_progress', 'U toku'), ('closed', 'Zatvoreno')], default='new', max_length=20, verbose_name='Status'),
        ),
    ]
