# Generated by Django 5.2.14 on 2026-06-02 04:32

import django.core.validators
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_primary', models.CharField(blank=True, max_length=30)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('email_primary', models.EmailField(blank=True, max_length=254)),
                ('email_inquiries', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('founder_name', models.CharField(blank=True, max_length=150)),
                ('founder_title_sr', models.CharField(blank=True, max_length=150)),
                ('founder_title_en', models.CharField(blank=True, max_length=150)),
                ('founder_photo', models.ImageField(blank=True, upload_to='site/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('founder_bio_sr', tinymce.models.HTMLField(blank=True)),
                ('founder_bio_en', tinymce.models.HTMLField(blank=True)),
                ('hero_headline_sr', models.CharField(blank=True, max_length=200)),
                ('hero_headline_en', models.CharField(blank=True, max_length=200)),
                ('hero_cta_text_sr', models.CharField(blank=True, max_length=80)),
                ('hero_cta_text_en', models.CharField(blank=True, max_length=80)),
                ('hero_image', models.ImageField(blank=True, upload_to='site/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('hero_video_url', models.URLField(blank=True)),
                ('google_analytics_id', models.CharField(blank=True, max_length=50)),
                ('facebook_pixel_id', models.CharField(blank=True, max_length=50)),
                ('seo_default_title', models.CharField(blank=True, max_length=70)),
                ('seo_default_description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Podešavanja sajta',
                'verbose_name_plural': 'Podešavanja sajta',
            },
        ),
    ]
