# Generated by Django 5.2.14 on 2026-06-05 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_video',
            field=models.FileField(blank=True, help_text='MP4 ili WebM video za hero pozadinu. Ako je postavljen, prikazuje se umesto hero slike (slika ostaje kao poster/fallback dok se video učita).', upload_to='site/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm'])]),
        ),
    ]
