# Generated by Django 5.2.14 on 2026-06-05 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_hero_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_video',
            field=models.FileField(blank=True, help_text='MP4, WebM ili MOV video za hero pozadinu. Ako je postavljen, prikazuje se umesto hero slike (slika ostaje kao poster/fallback dok se video učita). Napomena: MP4 je najsigurniji za sve browsere; MOV možda neće svirati u Chrome/Firefox.', upload_to='site/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov'])]),
        ),
    ]
