# Generated by Django 5.2.14 on 2026-06-05 20:15

import django.core.validators
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sitesettings_hero_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(blank=True, verbose_name='Adresa'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email_inquiries',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email za upite'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email_primary',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_pixel_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Facebook Pixel ID'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='founder_bio_en',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Biografija (EN)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='founder_bio_sr',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Biografija (SR)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='founder_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ime osnivača'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='founder_photo',
            field=models.ImageField(blank=True, upload_to='site/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Fotografija osnivača'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='founder_title_en',
            field=models.CharField(blank=True, max_length=150, verbose_name='Titula osnivača (EN)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='founder_title_sr',
            field=models.CharField(blank=True, max_length=150, verbose_name='Titula osnivača (SR)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Google Analytics ID'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_cta_text_en',
            field=models.CharField(blank=True, max_length=80, verbose_name='Hero dugme — tekst (EN)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_cta_text_sr',
            field=models.CharField(blank=True, max_length=80, verbose_name='Hero dugme — tekst (SR)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_headline_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Hero naslov (EN)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_headline_sr',
            field=models.CharField(blank=True, max_length=200, verbose_name='Hero naslov (SR)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='site/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Hero slika'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_video',
            field=models.FileField(blank=True, help_text='MP4, WebM ili MOV video za hero pozadinu. Ako je postavljen, prikazuje se umesto hero slike (slika ostaje kao poster/fallback dok se video učita). Napomena: MP4 je najsigurniji za sve browsere; MOV možda neće svirati u Chrome/Firefox.', upload_to='site/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov'])], verbose_name='Hero video'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_video_url',
            field=models.URLField(blank=True, verbose_name='Hero video URL (zastarelo)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_primary',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='seo_default_description',
            field=models.TextField(blank=True, verbose_name='SEO podrazumevani opis'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='seo_default_title',
            field=models.CharField(blank=True, max_length=70, verbose_name='SEO podrazumevani naslov'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp broj'),
        ),
    ]
