# Generated by Django 5.2.14 on 2026-06-02 04:32

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('title_sr', models.CharField(max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('content_sr', tinymce.models.HTMLField()),
                ('content_en', tinymce.models.HTMLField(blank=True)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Stranica',
                'verbose_name_plural': 'Stranice',
            },
        ),
    ]
