# Generated by Django 5.2.14 on 2026-06-05 20:15

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_seed_static_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content_en',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Sadržaj (EN)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content_sr',
            field=tinymce.models.HTMLField(verbose_name='Sadržaj (SR)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktivna'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta opis (SEO)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70, verbose_name='Meta naslov (SEO)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.CharField(max_length=100, unique=True, verbose_name='Slug (URL)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Naslov (EN)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title_sr',
            field=models.CharField(max_length=200, verbose_name='Naslov (SR)'),
        ),
    ]
