# Generated by Django 5.2.14 on 2026-06-02 04:32

import django.core.validators
import django.db.models.deletion
import tinymce.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sr', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('interior', 'Enterijer'), ('exterior', 'Eksterijer'), ('building', 'Zgrada'), ('legal', 'Pravno')], max_length=20)),
            ],
            options={
                'verbose_name': 'Karakteristika',
                'verbose_name_plural': 'Karakteristike',
                'ordering': ['category', 'name_sr'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('for_sale', 'Na prodaju'), ('for_rent', 'Za izdavanje'), ('price_on_request', 'Cena na upit'), ('sold', 'Prodato'), ('rented', 'Izdato')], max_length=20)),
                ('collection_type', models.CharField(choices=[('signature', 'Signature'), ('private', 'Privatna kolekcija'), ('off_market', 'Off-market')], max_length=20)),
                ('property_type', models.CharField(choices=[('stan', 'Stan'), ('kuca', 'Kuća'), ('penthouse', 'Penthouse'), ('vila', 'Vila'), ('komercijalno', 'Komercijalno'), ('zemljiste', 'Zemljište')], max_length=20)),
                ('location_city', models.CharField(max_length=100)),
                ('location_district', models.CharField(max_length=100)),
                ('location_address', models.CharField(blank=True, max_length=255)),
                ('show_address', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_on_request', models.BooleanField(default=False)),
                ('area_sqm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('area_total_sqm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('total_floors', models.IntegerField()),
                ('parking_spaces', models.IntegerField()),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('description_sr', tinymce.models.HTMLField()),
                ('description_en', tinymce.models.HTMLField()),
                ('description_fr', tinymce.models.HTMLField(blank=True)),
                ('hero_image', models.ImageField(upload_to='properties/hero/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('floor_plan', models.FileField(blank=True, upload_to='properties/floorplans/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp'])])),
                ('virtual_tour_url', models.URLField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.TextField(blank=True)),
                ('features', models.ManyToManyField(blank=True, related_name='properties', to='properties.propertyfeature')),
            ],
            options={
                'verbose_name': 'Nekretnina',
                'verbose_name_plural': 'Nekretnine',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/gallery/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('is_hero', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'verbose_name': 'Slika nekretnine',
                'verbose_name_plural': 'Slike nekretnina',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_active'], name='properties__is_acti_78cc81_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['collection_type'], name='properties__collect_ed03e5_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status'], name='properties__status_6427a0_idx'),
        ),
    ]
