# Generated by Django 5.2.14 on 2026-06-05 20:15

import django.core.validators
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='area_sqm',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Stambena površina (m²)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='area_total_sqm',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ukupna površina (m²)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(verbose_name='Kupatila'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(verbose_name='Spavaće sobe'),
        ),
        migrations.AlterField(
            model_name='property',
            name='collection_type',
            field=models.CharField(choices=[('signature', 'Signature'), ('private', 'Privatna kolekcija'), ('off_market', 'Off-market')], max_length=20, verbose_name='Tip kolekcije'),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Kreirano'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description_en',
            field=tinymce.models.HTMLField(verbose_name='Opis (EN)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description_fr',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Opis (FR)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description_sr',
            field=tinymce.models.HTMLField(verbose_name='Opis (SR)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='properties', to='properties.propertyfeature', verbose_name='Karakteristike'),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor',
            field=models.IntegerField(verbose_name='Sprat'),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor_plan',
            field=models.FileField(blank=True, upload_to='properties/floorplans/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp'])], verbose_name='Osnova (floor plan)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='hero_image',
            field=models.ImageField(upload_to='properties/hero/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Glavna slika'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktivna'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Izdvojena'),
        ),
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Geografska širina'),
        ),
        migrations.AlterField(
            model_name='property',
            name='location_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresa'),
        ),
        migrations.AlterField(
            model_name='property',
            name='location_city',
            field=models.CharField(max_length=100, verbose_name='Grad'),
        ),
        migrations.AlterField(
            model_name='property',
            name='location_district',
            field=models.CharField(max_length=100, verbose_name='Deo grada / opština'),
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Geografska dužina'),
        ),
        migrations.AlterField(
            model_name='property',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta opis (SEO)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70, verbose_name='Meta naslov (SEO)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='parking_spaces',
            field=models.IntegerField(verbose_name='Parking mesta'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Cena (€)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_on_request',
            field=models.BooleanField(default=False, verbose_name='Cena na upit'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('stan', 'Stan'), ('kuca', 'Kuća'), ('penthouse', 'Penthouse'), ('vila', 'Vila'), ('komercijalno', 'Komercijalno'), ('zemljiste', 'Zemljište')], max_length=20, verbose_name='Tip nekretnine'),
        ),
        migrations.AlterField(
            model_name='property',
            name='show_address',
            field=models.BooleanField(default=False, verbose_name='Prikaži adresu'),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug (URL)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('for_sale', 'Na prodaju'), ('for_rent', 'Za izdavanje'), ('price_on_request', 'Cena na upit'), ('sold', 'Prodato'), ('rented', 'Izdato')], max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Naslov'),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_floors',
            field=models.IntegerField(verbose_name='Ukupno spratova'),
        ),
        migrations.AlterField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ažurirano'),
        ),
        migrations.AlterField(
            model_name='property',
            name='virtual_tour_url',
            field=models.URLField(blank=True, verbose_name='URL virtuelne ture'),
        ),
        migrations.AlterField(
            model_name='property',
            name='year_built',
            field=models.IntegerField(blank=True, null=True, verbose_name='Godina izgradnje'),
        ),
        migrations.AlterField(
            model_name='propertyfeature',
            name='category',
            field=models.CharField(choices=[('interior', 'Enterijer'), ('exterior', 'Eksterijer'), ('building', 'Zgrada'), ('legal', 'Pravno')], max_length=20, verbose_name='Kategorija'),
        ),
        migrations.AlterField(
            model_name='propertyfeature',
            name='icon',
            field=models.CharField(max_length=50, verbose_name='Ikonica'),
        ),
        migrations.AlterField(
            model_name='propertyfeature',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='Naziv (EN)'),
        ),
        migrations.AlterField(
            model_name='propertyfeature',
            name='name_sr',
            field=models.CharField(max_length=100, verbose_name='Naziv (SR)'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255, verbose_name='Opis slike'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='properties/gallery/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Slika'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='is_hero',
            field=models.BooleanField(default=False, verbose_name='Glavna slika galerije'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Redosled'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='Nekretnina'),
        ),
    ]
