# Generated by Django 5.2.14 on 2026-06-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_area_sqm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyfeature',
            name='icon',
            field=models.CharField(blank=True, help_text='Opciono. Slug ikonice (npr. pool, garage, elevator). Trenutno se prikazuje generička ikonica za sve karakteristike; vrednost je rezervisana za buduće setove ikonica.', max_length=50, verbose_name='Ikonica'),
        ),
    ]
