# Generated by Django 5.2.14 on 2026-06-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_propertyfeature_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyfeature',
            name='icon',
            field=models.CharField(blank=True, choices=[('air-conditioning', 'Klima uređaj'), ('underfloor-heating', 'Podno grejanje'), ('fireplace', 'Kamin'), ('kitchen', 'Ugradna kuhinja'), ('wardrobe', 'Garderober / vešalica'), ('smart-home', 'Pametna kuća'), ('terrace', 'Terasa'), ('pool', 'Bazen'), ('garden', 'Vrt / drvo'), ('view', 'Pogled'), ('bbq', 'Roštilj'), ('elevator', 'Lift'), ('garage', 'Garaža'), ('parking', 'Parking'), ('concierge', 'Recepcija / zvonce'), ('cctv', 'Video nadzor'), ('storage', 'Ostava / kutija'), ('registered', 'Uknjiženo (dokument)'), ('no-encumbrance', 'Bez tereta (štit)'), ('permit', 'Dozvola (pečat)'), ('wine-cellar', 'Vinski podrum'), ('security', 'Obezbeđenje / alarm'), ('gym', 'Teretana'), ('jacuzzi', 'Đakuzi / spa'), ('intercom', 'Interfon'), ('sauna', 'Sauna')], help_text='Izaberite ikonicu koja se prikazuje uz karakteristiku na stranici nekretnine. Ostavite prazno za generičku ikonicu (kvačica).', max_length=50, verbose_name='Ikonica'),
        ),
    ]
